<?php

namespace WPKirk\WPBones\View\Assets;

/**
 * AdminAppsAssetEnqueuer class
 *
 * Specialized asset enqueuer for React/WordPress apps bundles in the admin area.
 * This class handles the specific requirements for enqueueing modern JavaScript
 * applications built with tools like @wordpress/scripts, including:
 * - Loading asset dependency files (.asset.php)
 * - Setting up script translations
 * - Managing module CSS files
 *
 * @package WPKirk\WPBones\View\Assets
 */
class AdminAppsAssetEnqueuer extends AssetEnqueuer
{
  /**
   * Get the base path for apps scripts.
   *
   * Returns the URL path to the apps directory where React bundles are located.
   *
   * @return string The base URL path for apps scripts.
   */
  protected function getScriptBasePath(): string
  {
    return $this->container->apps;
  }

  /**
   * Get the base path for apps styles.
   *
   * Returns the URL path to the apps directory where module CSS files are located.
   *
   * @return string The base URL path for apps styles.
   */
  protected function getStyleBasePath(): string
  {
    return $this->container->apps;
  }

  /**
   * Enqueue a single script with React bundle specific handling.
   *
   * This method overrides the parent to handle React bundles which require:
   * - Loading dependencies from .asset.php files
   * - Setting up WordPress script translations
   * - Default 'wp-element' dependency for React support
   *
   * @param array $script The script data array.
   *
   * @return void
   */
  protected function enqueueScript(array $script): void
  {
    // Load dependencies and version from the .asset.php file generated by @wordpress/scripts
    $assetFile = $this->container->basePath . '/public/apps/' . $script['name'] . '.asset.php';
    $assetData = file_exists($assetFile) ? include $assetFile : ['dependencies' => [], 'version' => ''];

    $dependencies = $assetData['dependencies'] ?? ['wp-element'];
    $version = $assetData['version'] ?? $script['ver'] ?? '';

    $src = $this->getScriptBasePath() . '/' . $script['name'] . '.js';

    wp_enqueue_script(
      $script['name'],
      $src,
      $dependencies,
      $version,
      true // Always load in footer for React apps
    );

    // Set up script translations for internationalization
    wp_set_script_translations(
      $script['name'],
      $this->container->TextDomain,
      $this->container->basePath . '/' . $this->container->DomainPath
    );
  }

  /**
   * Enqueue a single style for React apps.
   *
   * This method handles the module CSS files that are generated alongside
   * the JavaScript bundles by @wordpress/scripts.
   *
   * @param array $style The style data array.
   *
   * @return void
   */
  protected function enqueueStyle(array $style): void
  {
    $src = $this->getStyleBasePath() . '/' . $style['name'] . '.css';

    wp_enqueue_style(
      $style['name'],
      $src,
      $style['deps'] ?? [],
      $style['ver'] ?? '',
      $style['media'] ?? 'all'
    );
  }
}
